spring.datasource.url=jdbc:postgresql://localhost:5432/habittracker
spring.datasource.username=postgres
spring.datasource.password=Submarino2_
spring.security.user.name=admin
spring.security.user.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
